### ISSUE TITLE
Error on no match

### ISSUE THREAD

**Issue by isTravis** [tilgovi/dom-anchor-text-quote#10]
Howdy! Thanks for your work on this!

When calling `toRange`, if there is no match, an error is thrown. This seems a bit extreme and requires me to use a try, catch. Any chance this could instead simply return null? 

I may be missing something that makes the error the right solution, so feel free to guide me if I'm astray with this request :)

Thanks!

**Comment by tilgovi** [comment]
@robertknight does this change make sense to you?

**Comment by tilgovi** [comment]
@robertknight I just wanted to alert you as you may be the primary consumer and I know you've got a PR in flight to use the newest version.

**Comment by robertknight** [comment]
> @robertknight does this change make sense to you?

Yes, since lack of a match is an expected/normal failure (ala. string.match(regex)) rather than programmer error. Since it is a breaking change, it should be a major version bump.

**Comment by tilgovi** [comment]
Published as v4.0.0.

**Comment by isTravis** [comment]
Awesome - thanks so much for the quick turn around on this!
