### ISSUE TITLE
annotation triggers Uncaught IndexSizeError: Failed to execute 'splitText' on 'Text': The offset 102 is larger than the Text node's length.

### ISSUE THREAD

**Issue by judell** [tilgovi/dom-anchor-text-quote#2]
The URL: http://sitc.isoveradev.com/research-papers/seeing-forest-trees/university

The annotation: https://hypothes.is/api/annotations/2osQqDLrQk-xCK2q3xbMPA

```javascript
{
      "exact": "Recently reported reductions in Brazilian rainforest clearing over the past decade (5) were confirmed,",
       "prefix": "red at 62.1\u00b0N, 123.4\u00b0E.\n\n\t\t\u00a0\n\n\n\t",
       "type": "TextQuoteSelector",
       "suffix": " as annual forest loss decreased"
}
```
The code that throws an exception:

```javascript
function attach_annotation(category, text, exact, prefix) {
  var TextQuoteAnchor = require ('dom-anchor-text-quote')
  var $ = require('jQuery');
  var root = window.$('body')[0];
  console.log(root);
  var tqa = new TextQuoteAnchor(root, exact, {'prefix':prefix});
  var range = tqa.toRange();
  var container  = range.startContainer;
  var text_node = container.splitText(range.startOffset);
  text_node.splitText(exact.length)
  $(text_node).wrap('<a class="annotate ' + category + '" href="#" title="' + text + '" data-hasqtip="true"></a>')
}```

**Comment by tilgovi** [comment]
The code is wrong. It's assuming that `startContainer` === `endContainer` and trying to split this node at (`startOffset`, `endOffset`].

**Comment by tilgovi** [comment]
However, there are intervening anchor tags and such. The `startOffset` is 2 while the `endOffset` is 17. There are whole nodes between the start and end container that take up the remainder of the `length - (17 - 2) = 85` characters.

For instance, `range.endContainer.textContent.slice(0, range.endOffset)` yields ") were confirmed,". The start container ands at the left paren, where an anchor element starts.

**Comment by judell** [comment]
i now remember what happened, i was planning to work out how to cross text node boundaries and never got around to it

meanwhile i'm on a fresh machine with all the node packages reinstalled, i'm missing the one that provides XPathRange.Range.sniff, can't remember where that came from

**Comment by judell** [comment]
i now remember what happened, i was planning to work out how to cross text node boundaries and never got around to it

meanwhile i'm on a fresh machine with all the node packages reinstalled, i'm missing the one that provides XPathRange.Range.sniff, can't remember where that came from

**Comment by tilgovi** [comment]
You want xpath-range=0.0.6 I've been stripping that library down to almost nothing and pulling out the rest, getting rid of the classes in favor of functions over the platform Range objects.

You can use the old version explicitly if it's easier for now.

**Comment by judell** [comment]
Got it, thanks.

Is there an example lying around anywhere that shows how to wrap a
selection that crosses text node boundaries?

**Comment by tilgovi** [comment]
Using the old xpath-range, I think it's this:

```js
var normedRange = xpathRange.sniff(range).normalize(root);
var textNodes = normedRange.textNodes();

// Using jQuery maybe works?
$(textNodes).wrap('<span class="highlight"></span>');

// Else, you can do it the vanilla DOM way.
for (var i = 0, len = textNodes.length ; i < len ; i++) {
  var node =  textNodes[i];
  var hl = document.createElement('span');
  hl.className = 'highlight';
  node.parentNode.replaceChild(hl, node);
  hl.appendChild(node);
}
```

**Comment by judell** [comment]
Yeah, that part I get. It's the method for splitting and gathering the right set of nodes when startContainer != endContainer that I'm after. You showed me once but I failed to capture it :-(

**Comment by tilgovi** [comment]
You shouldn't have to deal with it if you're using the old `xpath-range`. The `normalize` method splits both ends and `textNodes` gives all the text nodes and all of them are guaranteed to be fully included in the range.

**Comment by judell** [comment]
That seems to work like a champ. Thanks much!
