### ISSUE TITLE
babelify needs to be a core dependency

### ISSUE THREAD

**Issue by BigBlueHat** [tilgovi/dom-anchor-text-quote#3]
Right now, I get this when I use `dom-anchor-text-quote` via browserify:

```
Error: Cannot find module 'babelify' from '/Users/byoung/dev/demo-dom-anchor-text-quote/node_modules/dom-anchor-text-quote'
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:107:15)
```

**Comment by tilgovi** [comment]
This is resolved now in the packaging on master and it shouldn't require `babelify` in the consumer.

**Comment by robertknight** [comment]
> This is resolved now in the packaging on master and it shouldn't require babelify in the consumer.

Thanks @tilgovi - I ran into problems with this a while back when attempting to use the current version of Babelify (using Babel 6.x) in the Hypothesis client alongside the older Babel 5.x version that was (is?) used in these packages.

**Comment by tilgovi** [comment]
@robertknight note that the APIs have changed and are now simple functions instead of having classes. I also haven't yet updated dom-anchor-fragment, although that one's dead simple.

**Comment by robertknight** [comment]
> @robertknight note that the APIs have changed and are now simple functions instead
> of having classes.

👍
