### ISSUE TITLE
`toRange` is missing when included via `<script>`

### ISSUE THREAD

**Issue by BigBlueHat** [tilgovi/dom-anchor-text-quote#4]
Haven't quite figured this one out yet either...
http://jsbin.com/gocumaviti/edit?js,console,output

**Comment by csarven** [comment]
Can confirm that I'm experiencing the same issue.

**Comment by tilgovi** [comment]
I've abandoned shipping this and my other similar modules as universal modules. Instead, they are published to npm as ES5 CommonJS modules. If anyone needs to package these as standalone scripts, they can run the npm package through a UMD bundler of their choice.
