### ISSUE TITLE
Naming's a bit confusing

### ISSUE THREAD

**Issue by BigBlueHat** [tilgovi/dom-anchor-text-quote#5]
For instance:

```javascript
var TextQuoteAnchor = require('dom-anchor-text-quote');
```

I keep getting them backwards...

**Comment by tilgovi** [comment]
:+1:

I've been experimenting on the dom-anchor-text-position repo with eliminating the classes for a more streamlined function-focused API. At that point, there's no "anchor" anymore, just selectors and ranges.

```js
var textQuote = require('dom-anchor-text-quote');
var range = textQuote.toRange(/* ... */)
```

**Comment by tilgovi** [comment]
I've done this de-OOP'ing.

Consider `dom-anchor` the namespace. "Selector" is overloaded, and these libraries do both selection and its opposite (identification, description), so I'm keeping the "anchor" part even though there is no such class anymore.
