### ISSUE TITLE
options not passed to toPositionAnchor

### ISSUE THREAD

**Issue by judell** [tilgovi/dom-anchor-text-quote#8]
I'm not sure what's going on in the translation from ES6 but in the generated code, here:

    key: 'toPositionAnchor',
    value: function toPositionAnchor() {
      var options = arguments.length <= 0 || arguments[0] === undefined ? {} : arguments[0];

`arguments` has gone missing and so there seems to be no way to call this:

`var tqa = new TextQuoteAnchor(document.body, exact, {'prefix':prefix, 'hint':0});`

And have the hint available in toPositionAnchor

**Comment by robertknight** [comment]
> https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/arguments

[arguments](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/arguments) is an object available in any JS function which can be used to access the list of function arguments. This allows functions to support arbitrary numbers of parameters.

What this code does is set `options` to the first argument to the function, if there is one, or an empty object (`{}`) otherwise.

**Comment by robertknight** [comment]
In other words, the generated code is a correct translation of the ES6 code `toPositionAnchor(options = {})`.

Stepping back for a moment, what is the original problem you were having?

**Comment by judell** [comment]
Some annotations were mis-anchored in a Science in the Classroom article. Occurrences near the top of the document were missed, and instead occurrences later in the doc were anchored. The reason seems to be that in the generated code, although the constructor gets the hint:

![image](https://cloud.githubusercontent.com/assets/46509/16930442/0fe99942-4cf1-11e6-810e-5cf1094808de.png)

it's missing by the time `toPositionAnchor()` is called:

![image](https://cloud.githubusercontent.com/assets/46509/16930490/4bfd5478-4cf1-11e6-801d-e27d25b6494d.png)

Forcing the hint to be zero at that point appears to be an acceptable workaround for the moment.

**Comment by tilgovi** [comment]
`toPositionAnchor` takes an options argument that can contain the `hint`. The hint is not part of the text quote selector and so it's not an instance attribute.

Is it onerous to pass the same context—the one with prefix and hint in the screenshot—to the call to `toPositionAnchor()`?

**Comment by judell** [comment]
I think I see what's going on. 

1. build with browserify -s get_annotations https://github.com/judell/StandaloneAnchoring/blob/master/package.json#L7 

2. `new TextQuoteAnchor.default`  https://github.com/judell/StandaloneAnchoring/blob/master/src/index.js#L5

3. call get_annotations https://github.com/judell/StandaloneAnchoring/blob/master/index.html#L154

When @bigbluehat

**Comment by tilgovi** [comment]
`.default` is not a thing you should have to call. That's ES6 compatibility stuff. It should be the same as `new TextQuoteAnchor` I think.

**Comment by tilgovi** [comment]
It's possible the import is getting messed up. I packaged this as a UMD module, but I've been moving away from that for libraries. We saw problems with various dependencies on hypothesis/client in the past where UMD modules were tricked by globals into not exporting themselves as CommonJS libs when we required them.

**Comment by tilgovi** [comment]
This should be fixed on master and I'll make a release today or tomorrow.

**Comment by judell** [comment]
Thanks Randall!
